mysql:
  host: 'localhost'
  port: 3306
  database: 'detox_db'
  username: 'your_username'
  password: 'your_password'

# Auto-migrate from old schema on startup (recommended)
auto-migrate: true

visible-by-default: false
# requires PlaceholderAPI
display-name-placeholder: "%player_name%"
prefix-placeholder: "%luckperms_prefix%"
auto-green-text: true
dunced-prefix: "Dunced"
unmoderated-chat-prefix: "UC"
baseColor: GRAY
highlightColor: GOLD
dunceStar: false